# -*- coding: utf-8 -*-
"""BLIP-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HB7KmD6q7q3g7l3vvrYrBzHSQ2mQ_Iu-
"""

# CELL 1
!pip install transformers accelerate pillow --quiet

# CELL 2
from transformers import Blip2Processor, Blip2ForConditionalGeneration
from PIL import Image
import torch
from google.colab import files

# CELL 3
model_id = "Salesforce/blip2-flan-t5-xl"

processor = Blip2Processor.from_pretrained(model_id)
model = Blip2ForConditionalGeneration.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto"
)

# CELL 4
uploaded = files.upload()
image_path = list(uploaded.keys())[0]
image = Image.open(image_path).convert("RGB")
image

# CELL 5
inputs = processor(
    images=image,
    text="Describe this image.",
    return_tensors="pt"
).to(model.device)

# CELL 6
generated_ids = model.generate(
    **inputs,
    max_new_tokens=64
)

caption = processor.batch_decode(
    generated_ids,
    skip_special_tokens=True
)[0]

print("Generated Caption:")
print(caption)