# -*- coding: utf-8 -*-
"""LDM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sfvDHXLezs_8-0jRMaJqiPFldPl7-Ev1
"""

# Cell 1
!pip install -q diffusers transformers accelerate safetensors

# Cell 2
import torch
from diffusers import AutoPipelineForText2Image

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

pipe = AutoPipelineForText2Image.from_pretrained(
    "stabilityai/sd-turbo",
    torch_dtype=torch.float16,
    variant="fp16"
).to(device)

# CELL 3: Prompt box

import ipywidgets as widgets
from IPython.display import display, clear_output

prompt_box = widgets.Text(
    value="",
    description="Prompt:",
    placeholder="Type your prompt and press Enter"
)

output = widgets.Output()

def handle_submit(change):
    with output:
        clear_output()
        global prompt
        prompt = change["new"]
        print("Prompt received:", prompt)

prompt_box.observe(handle_submit, names='value')

display(prompt_box, output)

# Cell 4
from IPython.display import display

image = pipe(
    prompt,
    num_inference_steps=4,
    guidance_scale=0.0
).images[0]

display(image)