# -*- coding: utf-8 -*-
"""Mask2FormerSwin-B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zOxPOtJw-BHQUJj5AKEdRx0VeeQi-kEF
"""

# CELL 0 — Upload an image from your desktop and set image_name

from google.colab import files

uploaded = files.upload()  # opens file picker

# Grab the first uploaded file name
image_name = list(uploaded.keys())[0]

print(f"Image uploaded and ready: {image_name}")

# CELL 1 — Install + Imports
!pip install -q transformers accelerate opencv-python pillow

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from PIL import Image

import torch
from transformers import AutoImageProcessor, Mask2FormerForUniversalSegmentation

print("Environment ready.")

# CELL 2 — Load Mask2Former Swin-B COCO Panoptic

model_id = "facebook/mask2former-swin-base-coco-panoptic"

processor = AutoImageProcessor.from_pretrained(model_id)
model = Mask2FormerForUniversalSegmentation.from_pretrained(model_id).to("cuda")

print("Mask2Former Swin-B COCO Panoptic loaded.")

# CELL 3 — Count person (0), purse (26), backpack (24), chair (56), laptop (63), book (73)

def count_objects_in_image(image_path):
    # Load image
    img_bgr = cv2.imread(image_path)
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    pil_img = Image.fromarray(img_rgb)

    # Prepare inputs
    inputs = processor(images=pil_img, return_tensors="pt").to("cuda")

    # Run model
    with torch.no_grad():
        outputs = model(**inputs)

    # Panoptic post-processing
    result = processor.post_process_panoptic_segmentation(
        outputs,
        target_sizes=[pil_img.size[::-1]]
    )[0]

    segments_info = result["segments_info"]

    # COCO class IDs
    PERSON = 0
    BACKPACK = 24
    PURSE = 26
    CHAIR = 56
    LAPTOP = 63
    BOOK = 73

    # Count each category
    person_count   = sum(1 for seg in segments_info if seg["label_id"] == PERSON)
    purse_count    = sum(1 for seg in segments_info if seg["label_id"] == PURSE)
    backpack_count = sum(1 for seg in segments_info if seg["label_id"] == BACKPACK)
    chair_count    = sum(1 for seg in segments_info if seg["label_id"] == CHAIR)
    laptop_count   = sum(1 for seg in segments_info if seg["label_id"] == LAPTOP)
    book_count     = sum(1 for seg in segments_info if seg["label_id"] == BOOK)

    return (
        person_count,
        purse_count,
        backpack_count,
        chair_count,
        laptop_count,
        book_count,
        img_rgb,
        result["segmentation"]
    )


# Run the combined counter
persons, purses, backpacks, chairs, laptops, books, img_rgb, seg_map = count_objects_in_image(image_name)

print("=== OBJECT COUNTS ===")
print(f"People detected:    {persons}")
print(f"Purses detected:    {purses}")
print(f"Backpacks detected: {backpacks}")
print(f"Chairs detected:    {chairs}")
print(f"Laptops detected:   {laptops}")
print(f"Books detected:     {books}")

# CELL 4 — Visualize segmentation overlay (optional)

def visualize_segmentation(image_rgb, seg_map):
    seg = seg_map.cpu().numpy()
    colored = np.zeros_like(image_rgb)

    # Random colors for each instance
    unique_ids = np.unique(seg)
    rng = np.random.default_rng(42)

    colors = {uid: rng.integers(0, 255, size=3) for uid in unique_ids}

    for uid in unique_ids:
        colored[seg == uid] = colors[uid]

    blended = (0.6 * image_rgb + 0.4 * colored).astype(np.uint8)

    plt.figure(figsize=(10, 10))
    plt.imshow(blended)
    plt.axis("off")
    plt.title("Panoptic Segmentation Overlay")
    plt.show()

visualize_segmentation(img_rgb, seg_map)

# CELL 5 — Display segments_info (instance ID, class ID, confidence)

def display_segments_info(image_path):
    # Load image
    img_bgr = cv2.imread(image_path)
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    pil_img = Image.fromarray(img_rgb)

    # Prepare inputs
    inputs = processor(images=pil_img, return_tensors="pt").to("cuda")

    # Run model
    with torch.no_grad():
        outputs = model(**inputs)

    # Panoptic post-processing
    result = processor.post_process_panoptic_segmentation(
        outputs,
        target_sizes=[pil_img.size[::-1]]
    )[0]

    segments_info = result["segments_info"]

    # Print the list in your preferred format
    print("\n=== SEGMENTS INFO (All Detected Instances) ===")
    for seg in segments_info:
        print(f"ID: {seg['id']:>4} | Class: {seg['label_id']:>2} | Score: {seg.get('score', 1.0):.3f}")


# Run the display
display_segments_info(image_name)