# -*- coding: utf-8 -*-
"""ORLCNN273K.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9m6nEM3mKapYk-kk09-JvTGZyGGr87O
"""

# CELL 1 — Imports, config, device

import os
import zipfile
import urllib.request
from pathlib import Path
from typing import List, Tuple
import itertools

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

DATA_ROOT = Path("./data/orl_faces")
BATCH_SIZE = 32
NUM_WORKERS = 2
NUM_CLASSES = 40
IMG_HEIGHT, IMG_WIDTH = 112, 92
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

!mkdir -p data
!wget https://www.cl.cam.ac.uk/Research/DTG/attarchive/pub/data/att_faces.zip -O data/orl_faces.zip
!unzip -q data/orl_faces.zip -d data/
!mv data/att_faces data/orl_faces

!mkdir -p data
!unzip -o data/orl_faces.zip -d data/

!ls data

DATA_ROOT = Path("data")

# CELL 2 — ORL dataset setup

# ORL dataset has already been extracted directly into:
# data/orl_faces/
# containing s1, s2, ..., s40

orl_dir = DATA_ROOT

# Check
subjects = [d for d in orl_dir.iterdir() if d.is_dir() and d.name.startswith("s")]
print("Found subject folders:", len(subjects))
assert len(subjects) == 40, "Expected 40 subject folders (s1–s40)."

print("ORL directory set to:", orl_dir)

# CELL 3 — Build train/val/test split

class ORLDataset(Dataset):
    def __init__(self, samples: List[Tuple[Path, int]], transform=None):
        self.samples = samples
        self.transform = transform

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        img = Image.open(img_path).convert("L")
        if self.transform:
            img = self.transform(img)
        return img, label


def build_splits(orl_dir: Path):
    train, val, test = [], [], []

    subjects = sorted([d for d in orl_dir.iterdir() if d.is_dir() and d.name.startswith("s")])
    assert len(subjects) == 40

    for label, subj_dir in enumerate(subjects):
        images = sorted(list(subj_dir.glob("*.pgm")))
        assert len(images) == 10

        train_imgs = images[:6]
        val_imgs   = images[6:8]
        test_imgs  = images[8:10]

        train.extend([(p, label) for p in train_imgs])
        val.extend([(p, label) for p in val_imgs])
        test.extend([(p, label) for p in test_imgs])

    return train, val, test


train_samples, val_samples, test_samples = build_splits(orl_dir)
print(len(train_samples), len(val_samples), len(test_samples))

# CELL 4 — Transforms + DataLoaders

train_transform = transforms.Compose([
    transforms.Resize((IMG_HEIGHT, IMG_WIDTH)),
    transforms.RandomCrop((IMG_HEIGHT - 8, IMG_WIDTH - 8)),
    transforms.Resize((IMG_HEIGHT, IMG_WIDTH)),
    transforms.RandomHorizontalFlip(0.5),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5]),
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_HEIGHT, IMG_WIDTH)),
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5]),
])

train_dataset = ORLDataset(train_samples, train_transform)
val_dataset   = ORLDataset(val_samples, eval_transform)
test_dataset  = ORLDataset(test_samples, eval_transform)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

print("DataLoaders ready.")

# CELL 5 — ORLCNN model (263k params)

class ORLCNN(nn.Module):
    def __init__(self, embedding_dim=128, num_classes=40):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(1, 32, 5, padding=2),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(128, 128, 3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d((1, 1)),
        )

        # Embedding head
        self.embedding = nn.Linear(128, embedding_dim)

        # Classification head
        self.classifier = nn.Linear(embedding_dim, num_classes)

    def forward(self, x):
        x = self.features(x)
        x = torch.flatten(x, 1)
        emb = F.relu(self.embedding(x))
        logits = self.classifier(emb)
        return logits

    def extract_embeddings(self, x):
        """Used for verification accuracy."""
        x = self.features(x)
        x = torch.flatten(x, 1)
        emb = F.relu(self.embedding(x))
        return emb


model = ORLCNN().to(device)
print(model)

# CELL 6 — Training utilities

def accuracy_from_logits(logits, labels):
    """
    Computes simple classification accuracy.

    """
    preds = torch.argmax(logits, dim=1)
    correct = (preds == labels).sum().item()
    total = labels.size(0)
    return correct, total


def evaluate(model, loader, criterion):
    """
    Computes:
    - average loss
    - classification accuracy
    on the given loader (val or test)

    """
    model.eval()
    total_loss = 0.0
    total_correct = 0
    total_samples = 0

    with torch.no_grad():
        for imgs, labels in loader:
            imgs = imgs.to(device)
            labels = labels.to(device)

            logits = model(imgs)
            loss = criterion(logits, labels)

            total_loss += loss.item() * imgs.size(0)

            correct, total = accuracy_from_logits(logits, labels)
            total_correct += correct
            total_samples += total

    # SAFETY CHECK — prevents returning None
    if total_samples == 0:
        print("WARNING: evaluate() received an empty loader.")
        return 0.0, 0.0

    avg_loss = total_loss / total_samples
    avg_acc = total_correct / total_samples

    return avg_loss, avg_acc

# CELL 6.5 — Verification Accuracy (pairwise cosine similarity)

def compute_verification_accuracy(model, loader):
    """
    Computes face-verification accuracy using cosine similarity.
    """
    model.eval()
    all_embs = []
    all_labels = []

    # Extract embeddings for the entire loader
    with torch.no_grad():
        for imgs, labels in loader:
            imgs = imgs.to(device)
            emb = model.extract_embeddings(imgs)
            all_embs.append(emb.cpu())
            all_labels.append(labels)

    all_embs = torch.cat(all_embs)
    all_labels = torch.cat(all_labels)

    pos_sims = []
    neg_sims = []

    # Build all pairwise comparisons
    for i, j in itertools.combinations(range(len(all_labels)), 2):
        sim = F.cosine_similarity(
            all_embs[i].unsqueeze(0),
            all_embs[j].unsqueeze(0)
        ).item()

        if all_labels[i] == all_labels[j]:
            pos_sims.append(sim)
        else:
            neg_sims.append(sim)

    pos_sims = np.array(pos_sims)
    neg_sims = np.array(neg_sims)

    # Sweep thresholds from -1 to +1
    thresholds = np.linspace(-1, 1, 200)
    best_acc = 0.0

    for t in thresholds:
        tp = np.sum(pos_sims >= t)
        fn = np.sum(pos_sims < t)
        tn = np.sum(neg_sims < t)
        fp = np.sum(neg_sims >= t)

        acc = (tp + tn) / (tp + tn + fp + fn)
        best_acc = max(best_acc, acc)

    return best_acc

# CELL 7 — Training loop

from tqdm import tqdm

num_epochs = 20
learning_rate = 1e-3
weight_decay = 1e-4

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)

best_verif = 0.0
best_state = None

for epoch in range(1, num_epochs + 1):
    model.train()
    total_loss = 0.0
    total_correct = 0
    total_samples = 0

    # -------------------------
    # Training loop
    # -------------------------
    for imgs, labels in tqdm(train_loader, desc=f"Epoch {epoch}/{num_epochs}", leave=False):
        imgs = imgs.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()
        logits = model(imgs)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * imgs.size(0)
        correct, total = accuracy_from_logits(logits, labels)
        total_correct += correct
        total_samples += total

    train_loss = total_loss / total_samples
    train_acc = total_correct / total_samples

    # -------------------------
    # Validation (classification)
    # -------------------------
    val_loss, val_acc = evaluate(model, val_loader, criterion)

    # -------------------------
    # Validation (verification accuracy)
    # -------------------------
    val_verif = compute_verification_accuracy(model, val_loader)

    # Track best model by verification accuracy
    if val_verif > best_verif:
        best_verif = val_verif
        best_state = {k: v.cpu() for k, v in model.state_dict().items()}

    # -------------------------
    # Epoch summary
    # -------------------------
    print(
        f"Epoch {epoch:02d} | "
        f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc*100:.2f}% | "
        f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc*100:.2f}% | "
        f"Val Verification Acc: {val_verif*100:.2f}%"
    )

# -------------------------
# Load best model
# -------------------------
if best_state is not None:
    model.load_state_dict(best_state)
    model.to(device)
    print(f"\nLoaded best model with Val Verification Accuracy = {best_verif*100:.2f}%")

# CELL 8 — Test-set verification accuracy

model.eval()

print("Computing test-set verification accuracy...")

test_verif = compute_verification_accuracy(model, test_loader)

print(f"\nTest Verification Accuracy = {test_verif*100:.2f}%")

# CELL 9 — Display all 40 ORL persons (one image per identity)

import os
import matplotlib.pyplot as plt
from PIL import Image

# --- Rebuild full_samples (required for Cell 9) ---
full_samples = train_samples + val_samples + test_samples

# --- Build a dictionary: label → first image path ---
samples_by_label = {}

for img_path, label in full_samples:
    if label not in samples_by_label:
        samples_by_label[label] = img_path
    if len(samples_by_label) == 40:
        break

# --- Load images in label order ---
ordered_labels = sorted(samples_by_label.keys())
ordered_imgs = [
    Image.open(samples_by_label[label]).convert("L")
    for label in ordered_labels
]

# --- Plot all 40 identities ---
plt.figure(figsize=(12, 10))
for i, (img, label) in enumerate(zip(ordered_imgs, ordered_labels)):
    plt.subplot(8, 5, i + 1)
    plt.imshow(img, cmap='gray')
    plt.title(f"Person {label}")
    plt.axis('off')

plt.suptitle("All 40 ORL Persons (One Sample Each)", fontsize=16)
plt.tight_layout()
plt.show()