# -*- coding: utf-8 -*-
"""TinyViT-Fashion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J8D_Fl-q8tLI64lL4mGETDu_mtADLhyU
"""

# CELL 1
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
import torchvision
import torchvision.transforms as T

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

# CELL 2
class PatchEmbedding(nn.Module):
    def __init__(self, img_size=32, patch_size=4, in_ch=1, emb_dim=128):
        super().__init__()
        self.patch_size = patch_size
        self.proj = nn.Conv2d(in_ch, emb_dim, kernel_size=patch_size, stride=patch_size)
        num_patches = (img_size // patch_size) ** 2
        self.pos_emb = nn.Parameter(torch.zeros(1, num_patches, emb_dim))

    def forward(self, x):
        x = self.proj(x)                      # (B, emb_dim, H', W')
        x = x.flatten(2).transpose(1, 2)      # (B, N, emb_dim)
        return x + self.pos_emb

# CELL 3
class MultiHeadSelfAttention(nn.Module):
    def __init__(self, emb_dim=128, num_heads=4):
        super().__init__()
        assert emb_dim % num_heads == 0
        self.num_heads = num_heads
        self.head_dim = emb_dim // num_heads

        self.qkv = nn.Linear(emb_dim, emb_dim * 3)
        self.out = nn.Linear(emb_dim, emb_dim)

    def forward(self, x):
        B, N, C = x.shape
        qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, self.head_dim)
        qkv = qkv.permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]

        attn = (q @ k.transpose(-2, -1)) / (self.head_dim ** 0.5)
        attn = attn.softmax(dim=-1)
        out = attn @ v
        out = out.transpose(1, 2).reshape(B, N, C)
        return self.out(out)

# CELL 4
class TransformerEncoderBlock(nn.Module):
    def __init__(self, emb_dim=128, num_heads=4, mlp_dim=256, dropout=0.1):
        super().__init__()
        self.norm1 = nn.LayerNorm(emb_dim)
        self.attn = MultiHeadSelfAttention(emb_dim, num_heads)
        self.norm2 = nn.LayerNorm(emb_dim)
        self.mlp = nn.Sequential(
            nn.Linear(emb_dim, mlp_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(mlp_dim, emb_dim),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        x = x + self.attn(self.norm1(x))
        x = x + self.mlp(self.norm2(x))
        return x

# CELL 5
class TinyViT(nn.Module):
    def __init__(self, img_size=32, patch_size=4, emb_dim=128, depth=2, num_heads=4, mlp_dim=256, num_classes=10):
        super().__init__()
        self.patch_embed = PatchEmbedding(img_size, patch_size, 1, emb_dim)
        self.cls_token = nn.Parameter(torch.zeros(1, 1, emb_dim))
        self.blocks = nn.ModuleList([
            TransformerEncoderBlock(emb_dim, num_heads, mlp_dim) for _ in range(depth)
        ])
        self.norm = nn.LayerNorm(emb_dim)
        self.head = nn.Linear(emb_dim, num_classes)

    def forward(self, x):
        B = x.size(0)
        x = self.patch_embed(x)
        cls = self.cls_token.expand(B, 1, -1)
        x = torch.cat([cls, x], dim=1)
        for blk in self.blocks:
            x = blk(x)
        x = self.norm(x)
        return self.head(x[:, 0])

# CELL 6
transform = T.Compose([
    T.Resize(32),
    T.ToTensor(),
    T.Normalize((0.5,), (0.5,))
])

train_set = torchvision.datasets.FashionMNIST(
    root="./data", train=True, download=True, transform=transform
)

test_set = torchvision.datasets.FashionMNIST(
    root="./data", train=False, download=True, transform=transform
)

train_loader = DataLoader(train_set, batch_size=128, shuffle=True, num_workers=2)
test_loader = DataLoader(test_set, batch_size=256, shuffle=False, num_workers=2)

# CELL 7
model = TinyViT().to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4, weight_decay=0.01)
criterion = nn.CrossEntropyLoss()

def train_epoch(epoch):
    model.train()
    total, correct = 0, 0
    for imgs, labels in train_loader:
        imgs, labels = imgs.to(device), labels.to(device)
        optimizer.zero_grad()
        logits = model(imgs)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        preds = logits.argmax(1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    print(f"Epoch {epoch}: Train Acc = {correct/total:.4f}")

def test():
    model.eval()
    total, correct = 0, 0
    with torch.no_grad():
        for imgs, labels in test_loader:
            imgs, labels = imgs.to(device), labels.to(device)
            preds = model(imgs).argmax(1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)
    print(f"Test Acc = {correct/total:.4f}")

# CELL 8
from tqdm import tqdm

EPOCHS = 10

for epoch in range(1, EPOCHS + 1):
    model.train()
    total, correct = 0, 0

    print(f"\nEpoch {epoch}/{EPOCHS}")
    pbar = tqdm(train_loader, desc=f"Training", leave=True)

    for imgs, labels in pbar:
        imgs, labels = imgs.to(device), labels.to(device)

        optimizer.zero_grad()
        logits = model(imgs)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        preds = logits.argmax(1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

        pbar.set_postfix({
            "loss": f"{loss.item():.4f}",
            "acc": f"{(correct/total):.4f}"
        })

    # ---- Test after each epoch ----
    model.eval()
    total_test, correct_test = 0, 0
    with torch.no_grad():
        for imgs, labels in test_loader:
            imgs, labels = imgs.to(device), labels.to(device)
            preds = model(imgs).argmax(1)
            correct_test += (preds == labels).sum().item()
            total_test += labels.size(0)

    print(f"Epoch {epoch} Summary → Train Acc: {correct/total:.4f} | Test Acc: {correct_test/total_test:.4f}")

# CELL 9 — visualize a batch of FashionMNIST images

import matplotlib.pyplot as plt
import numpy as np

# get one batch
images, labels = next(iter(train_loader))

# unnormalize helper
def unnormalize(img):
    return img * 0.5 + 0.5  # reverse Normalize((0.5,), (0.5,))

# class names for FashionMNIST
classes = [
    "T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
    "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"
]

# show 16 images
plt.figure(figsize=(8, 8))
for i in range(16):
    plt.subplot(4, 4, i + 1)
    img = unnormalize(images[i]).squeeze(0).numpy()
    plt.imshow(img, cmap="gray")
    plt.title(classes[labels[i].item()])
    plt.axis("off")

plt.tight_layout()
plt.show()